import = [
	"~/.config/alacritty/themes/themes/dayfox.toml"
]

[mouse]
bindings = [
    { mouse = "Right", action = "Paste" },
]

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
	{ key = "V", mods = "Control", action = "Paste" },
        { key = "+", mods = "Control | Shift", action = "IncreaseFontSize" },
        { key = "_", mods = "Control | Shift", action = "DecreaseFontSize" },
	{ key = "T", mods = "Control", action = "CreateNewWindow" },
]

[window]
dimensions = { columns = 60, lines = 15 }
opacity = 0.9

[shell]
program = "/bin/zsh"
args = ["-l"]

[font]
size = 14

[cursor]
style = { shape = "Underline", blinking = "On" }
